stevegrubb/libcap-ng

utils/filecap.c

The correct API is to define _GNU_SOURCE, not internal __xxx symbols that
glibc happens to use.  Since libcap-ng already defines that, there's no
need to redefine it.

filecap: do not define internal glibc symbols

---

utils/filecap.c

This makes it easier for users/devs to triage the underlying failure.

filecap: include errno in failure messages

---

configure.ac
src/cap-ng.c

Commit 7759e6f8469eb33aef1a1d5eba5d300c3a8fcb63 broke compilation on
systems without pthread.h. So add a call to AC_CHECK_HEADERS in
configure.ac and put include <pthread.h> under HAVE_PTHREAD_H define
Fixes:
- http://autobuild.buildroot.net/results/6132f33fb282fda3c39deb292784b9006c9e7872
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Fix compilation without pthread.h

---

src/Makefile.am

as suggested by Simon McVittie in
https://github.com/stevegrubb/libcap-ng/issues/5 and Carlos O'Donell at
https://sourceware.org/bugzilla/show_bug.cgi?id=13502 mark the DSOs as
unloadable with -z nodelete to prevent crashes at fork
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904808
Fix: https://github.com/stevegrubb/libcap-ng/issues/5

Fix mark the DSOs as unloadable

---

utils/pscap.8
utils/pscap.c

I was a bit surprised to see the following entry in the output of `pscap` on my machine:
```
5752  5754  qazer       chromium          sys_admin +
```
Then I realized that the browser was working in the child user namespace, not in the initial one, so its `CAP_SYS_ADMIN` should not compromise my system.
This PR is a suggestion to make things clearer and mark processes running in the child user namespaces with an asterisk, e.g.:
```
5752  5754  qazer       chromium *          sys_admin +
```
Another example - with rootless containers:
```
1     5658  qazer       podman pause *      full
10728 10961 qazer       podman *            full
1     10973 qazer       conmon *            full
10973 10984 qazer       sh *                chown, dac_override, fowner, fsetid, kill, setgid, setuid, …
```

[pscap] Mark processes in child user namespaces with *.

---

configure.ac

If the pthread.h header is found, make sure library containing
"pthread_atfork" is added to the list of libraries against which to link.
On some hosts (e.g. openSUSE 15.1) "-lpthread" needs to be explicitly added
in order for the code to compile correctly.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>

configure.ac: add library if header found

---

src/cap-ng.c

Put pthread_atfork under #ifdef HAVE_PTHREAD_H block
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

src/cap-ng.c: fix build without threads

---

src/cap-ng.c

musl needs this as otherwise both __BYTE_ORDER and __BIG_ENDIAN are undefined.

include missing endian.h header

---

src/cap-ng.c

POSIX does not mandate malloc() to be async-safe so calling malloc()
from child after fork may result in a deadlock. This resulted in
libvirtd deadlock with musl libc due to a call to capng_apply.
Fix this by storing the state on stack instead of using
capng_save_state().
Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11602

Avoid malloc/free in capng_apply

---

configure.ac
src/Makefile.am

It is possible (though nowadays rare) for a system to lack support
for ambient caps. For that case, libdrop_ambient is irrelevant and
breaks the build, so don't try to build it.
This change addresses issue #24

Make libdrop_ambient build conditional

---

bindings/python/Makefile.am
bindings/python3/Makefile.am
configure.ac

Currently the path to capability.h is hardcoded. When cross compiling
the host capabiity.h may be different to the target copy, leading
to different options being encoded in the python bindings than
expected. This causes a reproducibility issue amongst other potential
problems.
Add a configure option to optionally specify the right path to the
correct header as its probably safer/more reliable than trying to
query the compiler to get the header path.
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

bindings/python: Allow hardcoded path to capability.h to be overridden

---

ChangeLog
src/cap-ng.c

The attribute constructor mechanism only works for shared library.
When _libcap_ng_ is linked as static library, we need to call the `init_lib()` function manually. This patch makes the function external, renames it to `capng_init()` (to be consistent with other functions) and adds a manual page for documentation.

Export capng_init() to be called when linked statically

---

bindings/python/test/capng-test.py

The shebang line is still restricting it to Python 2.
Removed end-of-line whitespace as well.
---
The placement of the testsuite is also a bit restricting.
It would be nice if it would be possible to test with Python 2, Python 3 or both.

Make Python test script compatible with Python 2 and Python 3.

---

docs/libdrop_ambient.7

This was installed in section 7, and the header specified section 3.
Since this isn't a library call I'm assuming section 7 is correct.

Change manual section and add whatis entry.

---

configure.ac

I noticed a missing comma here.  Without the comma, you get the warning message about requiring linux/magic.h regardless of whether or not the configure script found it.
Signed-off-by: David Cantrell <dcantrell@redhat.com>

Fix typo in configure.ac for the linux/magic.h header check.

---

configure.ac

Remove use deprecated distutils python module and use istead sysconfig.get_path()

remove use deprecated distutils python module

---

Makefile.am
README
README.md
docs/capng_apply.3
docs/capng_clear.3
docs/capng_fill.3
docs/capng_update.3
docs/capng_updatev.3
libcap-ng.spec
src/libcap-ng.pc.in

- POSIX is written in uppercase
- Split examples into a proper markdown list and separate code-blocks
- Drop empty NEWS file, we're using ChangeLog
- Remove README, ship README.md instead

Updated documentation

---

src/cap-ng.c

```
cap-ng.c: In function 'get_bounding_set':
cap-ng.c:447:16: error: expected ')' before ';' token
447 |   (int)getpid();
|                ^
|                )
cap-ng.c:477:11: error: expected ';' before '}' token
477 |  return 0;
|           ^
|           ;
478 | }
| ~          
cap-ng.c: In function 'get_ambient_set':
cap-ng.c:492:16: error: expected ')' before ';' token
492 |   (int)getpid();
|                ^
|                )
cap-ng.c:522:11: error: expected ';' before '}' token
522 |  return 0;
|           ^
|           ;
523 | }
| ~ 
```

Fix the syntax error in cap-ng.c

---

utils/pscap.c

It should be failed with an invalid PID argument(eg:pscap -p 1abcde).

Strengthen the checking of PID argument

---

bindings/python3/Makefile.am

48eebb2 replaced custom PYTHON3 variable with PYTHON by using standard AM_PATH_PYTHON macro. Makefile however still referred to old one. There's no need to set PYTHON explicitly anymore so drop it.
Fixes #53

Fix python path when invoking py-compile

---

src/libcap-ng.pc.in

The pkg-config file has License variable that allows you to set the license for the software. 
This sets LGPL-2.1-or-later to License.
Ref: https://github.com/pkgconf/pkgconf/blob/master/man/pc.5#L116

Add License variable to pkg-config file
